from src.model.models.network import Network
from src.model.models.fcn import FCN
from src.model.models.pspnet import PSPNet
from src.model.models.segnet import SegNet
from src.model.models.unet import UNet
from src.model.models.pan import PAN
from src.model.models.deeplab_v3 import DeepLabV3
from src.model.models.deeplab_v3_plus import DeepLabV3Plus
from src.model.models.refinenet import RefineNet
from src.model.models.denseaspp import DenseASPP
from src.model.models.bisegnet import BiSegNet
